name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.0

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

      # Add a new step to capture the name of the generated executable
      - name: Get Executable Name
        run: echo "::set-output name=executable_name::$(find . -type f -name '*.exe' -printf '%f\n')"

      # Add a new step to upload the built executable as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-app
          path: ${{ steps.electron-builder.outputs.executable_name }}

